version: '3.8'

services:
  prestashop:
    image: prestashop/prestashop:8.2
    restart: always
    ports:
      - "8000:80"
    environment:
      - DB_SERVER=db
      - DB_NAME=prestashop
      - DB_USER=admin
      - DB_PASSWORD=admin
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD=admin
      MYSQL_DATABASE=prestashop
      MYSQL_USER=admin
      MYSQL_PASSWORD=admin
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
